version: "3"

services:
  app:
    container_name: jackbarber_app
    image: node:14-alpine
    ports:
      - "3333:3333"
    working_dir: /usr/src/
    command: sh -c "npm run prod"
    volumes: 
      - .:/usr/src/
      - nodemodules:/usr/src/node_modules
    links:
      - postgres
      - mongo
      - redis

  postgres:
    container_name: jackbarber_postgres
    image: "postgres:9.4"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
     POSTGRES_PASSWORD: ${DB_PASS}
     POSTGRES_USER: ${DB_USER}

  mongo:
    container_name: jackbarber_mongo
    image: mongo
    volumes:
      - ./docker/mongo:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: jackbarber_redis
    image: redis
    volumes:
      - ./docker/redis:/redis/db
    ports:
      - "6379:6379"
volumes: 
  nodemodules: {}
